language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
install:
  - pip install pytest
script:
  - python -m pytest --doctest-modules --ignore=setup.py -p no:warnings