language: python
dist: xenial
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - "pip install pytest"
script:
  - "pytest --doctest-modules --ignore=setup.py -p no:warnings"